services:
  # stock services
  db:
    image: postgres
    env_file:
      - .env
    restart: always
  gateway:
    image: nginx
    ports:
      - $GATEWAYPORT:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    restart: always
    depends_on:
      - db
      - backend

  # custom services
  backend:
    build: ./backend
    env_file:
      - .env
    command: npm run db:reset ; npm run dev
    ports:
      - $PGPORT:5000
    volumes:
      - ./backend/src/:/app/src/
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - $NEXT_PUBLIC_FRONTENDPORT:3000
    volumes:
      - ./frontend/src/:/app/src/
      - ./frontend/public/:/app/public/
    depends_on:
      - backend
    env_file:
      - .env
