import { MapDetail } from "@/components/MapDetail";
import { gql, useQuery } from "@apollo/client";
import Head from "next/head";
import { useRouter } from "next/router";
import { Map } from "../../../../backend/src/entities/Map";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const GET_SCENARIO = gql`
  query Scenario($scenarioId: Int!) {
    scenario(scenarioId: $scenarioId) {
      title
      teaser
      fullStory
      credits
      bannerUrl
      maps {
        title
        pictureUrl
        description
        pointsOfInterest {
          id
          code
          title
          description
        }
      }
    }
  }
`;
export default function ScenarioPage() {
  const router = useRouter();

  const { loading, error, data } = useQuery(GET_SCENARIO, {
    variables: { scenarioId: Number(router.query.id) },
  });

  if (error) return <p>Error</p>;
  if (loading) return <p>Loading...</p>;
  if (!data) return <p>Not found</p>;

  return (
    <>
      <Head>
        <title>Roleet - Scenario: #1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>{data.scenario.title}</h1>
        <Tabs defaultValue="story" className="w-3/4 m-auto">
          <TabsList>
            <TabsTrigger value="story">Story</TabsTrigger>
            <TabsTrigger value="maps">Maps</TabsTrigger>
          </TabsList>
          <TabsContent value="story">
            <p>{data.scenario.fullStory}</p>
          </TabsContent>
          <TabsContent value="maps">
            {data.scenario.maps.map((map: Map) => (
              <MapDetail {...map} key={map.id} />
            ))}
          </TabsContent>
        </Tabs>
      </div>
    </>
  );
}
