"use client";
import ScenarioForm from "@/components/ScenarioForm";
import Head from "next/head";

export default function ScenarioPage() {
  return (
    <>
      <Head>
        <title>Roleet - Forge: Créer un Scenario</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ScenarioForm />
    </>
  );
}
