import { useGetScenariosQuery } from "@/generated/gqlQueries";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  const { loading, error, data } = useGetScenariosQuery();

  if (error) return <p>Error</p>;
  if (loading) return <p>Loading...</p>;
  if (!data) return <p>Not found</p>;

  return (
    <>
      <Head>
        <title>Roleet - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Scenarios disponibles</h2>
      <ul>
        {data.scenarios.map((scenarioData) => (
          <li key={scenarioData.id}>
            <Link href={`/scenarios/${scenarioData.id}`}>
              {scenarioData.title}
            </Link>
          </li>
        ))}
      </ul>

      <h2>Autres liens utiles</h2>
      <Link href="/scenarios/new">Création d&apos;un Scenario</Link>
    </>
  );
}
